version: "3.7"
services:
  client:
    depends_on:
      - server
    environment: 
      - serverlocation=server
    build:
      context: .
      dockerfile: client.Dockerfile
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
